"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const linkedList_1 = require("./exemples/linkedList");
// BasicListExemple.run();
// IterationListExemple.run();
// InsertOnlyIfListExemple.run();
// personListExemple.run();
// BasicStackExemple.run();
// MultipleBaseConversionStack.run();
// PolindromStackExemple.run();
// FactorialStackExemple.run();
// UnbalancedParenthesesStackExemple.run();
// InfinixExpressionStackExemple.run();
// BasicQueueExemple.run();
// SquareDanceQueueExemple.run();
// RadixSortQueueExemple.run();
// PriorityQueueExemple.run();
// DequeQueueExemple.run();
// BasicLinkedListExemple.run();
// BasicDLinkedListExemple.run();
linkedList_1.PostLinkedListExemple.run();
